-- Migration to create the 'todos' table in Supabase
-- Target database: Supabase PostgreSQL

CREATE TABLE IF NOT EXISTS "todos" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
